### ISSUE TITLE
Proxy request to external server

### ISSUE THREAD

**Issue by DanielFGray** [shellscape/webpack-serve#11]
I'm migrating from `create-react-app` (which if I'm not mistaken uses webpack-dev-server) allows a user to define a "proxy" setting to forward requests to a different url, for example I'd like to proxy requests from `/graphql` to `localhost:8080/graphql`

Is this possible with webpack-serve, or would I have to hard-code different API urls during dev vs prod?

**Comment by matheus1lva** [comment]
Hi! 
Yes!
Use the proxy option directly on the package json!

ps: this is `webpack-plugin-serve` option, but it looks really the same!

```

      middleware: (app, builtins) => {
        app.use(builtins.proxy('/graphql ', { target: 'http://10.10.10.1:1337/graphql' }));
      }
    })
  ]
};

```

**Comment by shellscape** [comment]
@DanielFGray what is being suggested is to  use webpack-plugin-serve as a better alternative (we maintain that plugin too), but you can also use the proxy options in this package as well.
