### ISSUE TITLE
"koa-webpack": "^5.1.0" is out of date

### ISSUE THREAD

**Issue by joacim-boive** [shellscape/webpack-serve#2]
There's a problem in koa-webpack < 5.2.2 as I guess you know. :)

https://github.com/shellscape/koa-webpack/pull/110

This should have a package.json looking something like this:
"koa-webpack": "^5.2.2"

**Comment by shellscape** [comment]
>   If you remove or skip this template, you'll make the 🐼 sad and the mighty god
  of Github will appear and pile-drive the close button from a great height
  while making animal noises.

Issue templates are not there to look pretty. If you can't take the time to fill them out, don't expect maintainers to take the time to address your issue. The next major version will not use `koa-webpack`. See the `next` branch, use [`webpack-plugin-serve`](https://www.npmjs.com/package/webpack-plugin-serve) instead.
