### ISSUE TITLE
'watch' needed in the target webpack config - not mentioned

### ISSUE THREAD

**Issue by pearofducks** [shellscape/webpack-serve#5]
Documentation Is:

- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

v3 is applying the [entry](https://github.com/shellscape/webpack-serve/blob/master/lib/plugin.js#L20) and [plugin](https://github.com/shellscape/webpack-serve/blob/master/lib/plugin.js#L37) for the user, but not `watch: true`. 

The README makes no mention of the fact this key is required for the plugin to function correctly, thus anyone picking the plugin up will see webpack compile and exit!

### Your Proposal for Changes

Either this should be applied for the user like _entry_ and _plugin_, or the user should be told they need this in their webpack config (just like webpack-plugin-serve does).

e.g.
`watch: true  // ← important: webpack and the server will continue to run in watch mode`

**Comment by shellscape** [comment]
Nice catch :beer: To be thorough, `watch: true` is only needed if `hmr: true` or `liveReload: true`. This is a change that should be made.
